app:
  security:
    jwt:
      issuer: budget-app
      secret: "9f9c2c9f1e1a4c3aa7d4b9d1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1"
      access-token-minutes: 60
    auth:
      max-failed-attempts: 5
      lock-minutes: 15
      verification-token-minutes: 1440
      verification-base-url: "http://localhost:8080/api/auth/verify-email?token="
      verification-from: "no-reply@budget-app.local"


spring:
  application:
    name: budget
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 810e67c078a134
    password: 142d9fd0e420b2
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/budget_app
    #    url: jdbc:postgresql://budget-postgres:5432/budget_app
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: 8080
