app:
  security:
    jwt:
      issuer: budget-app
      secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS"
      access-token-minutes: 60

spring:
  application:
    name: budget
  datasource:
    url: jdbc:postgresql://localhost:5432/budget_app
    #    url: jdbc:postgresql://budget-postgres:5432/budget_app
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect